library(tm)
library(wordcloud)
library(wordcloud2)
Joji<-readLines(choose.files())
document<-Corpus(VectorSource(Joji))
toSpace<-content_transformer(function(x,pattern)gsub(pattern,"",x))
document<-tm_map(document,content_transformer(tolower))
document<-tm_map(document, removeWords,stopwords("english"))
document<-tm_map(document,stripWhitespace)
document<-tm_map(document,removePunctuation)
inspect(document)
document2<-tm_map(document,stemDocument)
#term matrix
Dtm<-TermDocumentMatrix(document2)
freq<-colSums(as.matrix(Dtm))
length(freq)
ord<-order(freq,decreasing=T)
head(ord)
freq[head(ord)]
findFreqTerms(Dtm,lowfreq=1)
m<-as.matrix(Dtm)
v<-sort(rowSums(m),decreasing=T)
d<-data.frame(word=names(v),freq=v)
set.seed(1)
wordcloud(words=d$word,freq=d$freq,min.freq=1,random.order=F,color=brewer.pal(8,"Dark2"))
names(d)<-c("TERM","FREQ")
Subs<-subset(d,FREQ>=5)
ggplot(Subs,aes(x=TERM,y=FREQ))+geom_bar(stat="identity")+
  theme(axis.text.x=element_text(angle=45,hjust=1))

Joji_indie<-readLines(choose.files())
document<-Corpus(VectorSource(Joji_indie))
toSpace<-content_transformer(function(x,pattern)gsub(pattern,"",x))
document<-tm_map(document,content_transformer(tolower))
document<-tm_map(document, removeWords,stopwords("english"))
document<-tm_map(document,stripWhitespace)
document<-tm_map(document,removePunctuation)
inspect(document)
document2<-tm_map(document,stemDocument)
#term matrix
Dtm<-TermDocumentMatrix(document2)
freq<-colSums(as.matrix(Dtm))
length(freq)
ord<-order(freq,decreasing=T)
head(ord)
freq[head(ord)]
findFreqTerms(Dtm,lowfreq=1)
m<-as.matrix(Dtm)
v<-sort(rowSums(m),decreasing=T)
d<-data.frame(word=names(v),freq=v)
set.seed(1)
wordcloud(words=d$word,freq=d$freq,min.freq=1,random.order=F,color=brewer.pal(8,"Dark2"))
names(d)<-c("TERM","FREQ")
Subs<-subset(d,FREQ>=5)
ggplot(Subs,aes(x=TERM,y=FREQ))+geom_bar(stat="identity")+
  theme(axis.text.x=element_text(angle=45,hjust=1))


Joji_hiphop<-readLines(choose.files())
document<-Corpus(VectorSource(Joji_hiphop))
toSpace<-content_transformer(function(x,pattern)gsub(pattern,"",x))
document<-tm_map(document,content_transformer(tolower))
document<-tm_map(document, removeWords,stopwords("english"))
document<-tm_map(document,stripWhitespace)
document<-tm_map(document,removePunctuation)
document<-tm_map(document,toSpace,"-")
inspect(document)

document2<-tm_map(document,stemDocument)
#term matrix
Dtm<-TermDocumentMatrix(document2)
freq<-colSums(as.matrix(Dtm))
length(freq)
ord<-order(freq,decreasing=T)
head(ord)
freq[head(ord)]
findFreqTerms(Dtm,lowfreq=5)
m<-as.matrix(Dtm)
v<-sort(rowSums(m),decreasing=T)
d<-data.frame(word=names(v),freq=v)
library(wordcloud)
set.seed(1)
wordcloud(words=d$word,freq=d$freq,min.freq=1,random.order=F,
          color=brewer.pal(8,"Dark2"))
library(ggplot2)
names(d)<-c("TERM","FREQ")
Subs<-subset(d,FREQ>=5)
ggplot(Subs,aes(x=TERM,y=FREQ))+geom_bar(stat="identity")+
  theme(axis.text.x=element_text(angle=45,hjust=1))

